// ESix10 Daily Devotions — one per day of the year (repeats only once a year).
// Holiday-themed devotions auto-trigger on the real date (including ones that move each year).
// Each entry: [title, verse, reference, reflection]

export const DAILY_DEVOTIONS = [
  // ── JANUARY ──
  ["Strength in the Lord", "Be strong in the Lord and in his mighty power.", "Ephesians 6:10", "Your strength runs out. His does not. Start the year drawing from His."],
  ["A New Thing", "See, I am doing a new thing! Now it springs up; do you not perceive it?", "Isaiah 43:19", "What you leave behind this year matters less than what you let Him begin."],
  ["Press On", "Forgetting what is behind and straining toward what is ahead.", "Philippians 3:13", "You cannot move forward while clutching the past. Let it go and run."],
  ["Renewed Strength", "Those who hope in the Lord will renew their strength.", "Isaiah 40:31", "Bring your empty tank to Him before you try to run another mile."],
  ["First Things First", "But seek first his kingdom and his righteousness.", "Matthew 6:33", "Order the day around Him and everything else finds its place."],
  ["Steadfast", "Be steadfast, immovable, always abounding in the work of the Lord.", "1 Corinthians 15:58", "Steadfast means you do not move when it gets hard. Today, be the one who stays."],
  ["Guard the Gate", "Above all else, guard your heart, for everything you do flows from it.", "Proverbs 4:23", "What you let in becomes what comes out. Guard the gate today."],
  ["Lean Not", "Trust in the Lord with all your heart and lean not on your own understanding.", "Proverbs 3:5", "Your understanding is limited. His is not. Loosen your grip on figuring it all out."],
  ["Be Courageous", "Be strong and courageous. Do not be afraid; for the Lord your God will be with you wherever you go.", "Joshua 1:9", "Courage is not the absence of fear. It is moving because He goes with you."],
  ["One Day at a Time", "Therefore do not worry about tomorrow, for tomorrow will worry about itself.", "Matthew 6:34", "You only have today. Be faithful in it and let tomorrow keep its own weight."],
  ["Run the Race", "Let us run with perseverance the race marked out for us.", "Hebrews 12:1", "It is not a sprint and it is not optional. Lace up. Keep going."],
  ["Light to My Path", "Your word is a lamp for my feet, a light on my path.", "Psalm 119:105", "You do not need the whole road lit. Just the next step. Open the Word."],
  ["Cast Your Cares", "Cast all your anxiety on him because he cares for you.", "1 Peter 5:7", "You were not built to carry it all. Hand the weight to the One who can hold it."],
  ["Renew the Mind", "Be transformed by the renewing of your mind.", "Romans 12:2", "You are not stuck with the thoughts you woke up with. Feed your mind truth."],
  ["Chosen", "You did not choose me, but I chose you.", "John 15:16", "Before you ever reached for Him, He reached for you. You belong."],
  ["Be Still", "Be still, and know that I am God.", "Psalm 46:10", "Quiet is not weakness. Sometimes the strongest thing you do is stop and trust."],
  ["The Cornerstone", "With Christ Jesus himself as the chief cornerstone.", "Ephesians 2:20", "Build your life on the one thing that will not shift. Everything else is sand."],
  ["Walk by Faith", "For we live by faith, not by sight.", "2 Corinthians 5:7", "You will not always see the next step lit up. Walk anyway. He is already there."],
  ["Made New", "If anyone is in Christ, the new creation has come: The old has gone, the new is here.", "2 Corinthians 5:17", "Whatever you were is not what you are. He makes men and women new."],
  ["Strong and Capable", "I can do all this through him who gives me strength.", "Philippians 4:13", "Not in your own power. In His. That changes what is possible today."],
  ["Plans for You", "For I know the plans I have for you, plans to prosper you and not to harm you.", "Jeremiah 29:11", "You may not see the whole map. He does, and it is good."],
  ["Show Up", "Let us not give up meeting together, but encourage one another.", "Hebrews 10:25", "Community is built in the ordinary moments of showing up. Be there."],
  ["Speak Life", "The tongue has the power of life and death.", "Proverbs 18:21", "Your words build or destroy. Today, build someone."],
  ["Anchor for the Soul", "We have this hope as an anchor for the soul, firm and secure.", "Hebrews 6:19", "Storms come. An anchor is not for calm water. Drop it deep."],
  ["The Lord Fights", "The Lord will fight for you; you need only to be still.", "Exodus 14:14", "Not every battle is yours to win by force. Some you win by trusting."],
  ["Wisdom", "If any of you lacks wisdom, you should ask God, who gives generously.", "James 1:5", "Stop guessing. Ask. He is not stingy with direction."],
  ["Delight", "Take delight in the Lord, and he will give you the desires of your heart.", "Psalm 37:4", "When He becomes your delight, your wants start to line up with His."],
  ["No Condemnation", "Therefore, there is now no condemnation for those who are in Christ Jesus.", "Romans 8:1", "Shame is not from Him. Lay it down. You are not what you did."],
  ["Strength of My Heart", "My flesh and my heart may fail, but God is the strength of my heart.", "Psalm 73:26", "When you run out, He does not. He is the strength underneath your strength."],
  ["Commit Your Way", "Commit to the Lord whatever you do, and he will establish your plans.", "Proverbs 16:3", "Hand Him the work before you start it. Watch what He builds."],
  ["Faithful", "He who began a good work in you will carry it on to completion.", "Philippians 1:6", "You are not finished. He is not done. Trust the process He started."],

  // ── FEBRUARY ──
  ["Love First", "We love because he first loved us.", "1 John 4:19", "You do not manufacture love. You receive it from Him, then give it away."],
  ["Greatest of These", "And now these three remain: faith, hope and love. But the greatest of these is love.", "1 Corinthians 13:13", "Everything you do without love is just noise. Lead with love today."],
  ["Patient and Kind", "Love is patient, love is kind.", "1 Corinthians 13:4", "Start there. Patient with the people closest to you. Kind when it is inconvenient."],
  ["Above All", "Above all, love each other deeply, because love covers over a multitude of sins.", "1 Peter 4:8", "Love does not keep score. It covers. Extend that today."],
  ["Lay Down", "Greater love has no one than this: to lay down one's life for one's friends.", "John 15:13", "Love is measured in what it gives up. Who needs you to lay something down?"],
  ["Devoted", "Be devoted to one another in love. Honor one another above yourselves.", "Romans 12:10", "Honor is a choice to lift someone higher than yourself. Make it today."],
  ["Reconcile", "If your brother or sister has something against you... go and be reconciled.", "Matthew 5:23-24", "Do not let it sit. Make the call. Mend what you can."],
  ["Bear With", "Bear with each other and forgive one another.", "Colossians 3:13", "People will let you down. Forgiveness is how you keep walking together."],
  ["A Friend Loves", "A friend loves at all times, and a brother is born for a time of adversity.", "Proverbs 17:17", "Anyone can show up in the good times. Be the one who shows up in the hard ones."],
  ["Gentle Answer", "A gentle answer turns away wrath, but a harsh word stirs up anger.", "Proverbs 15:1", "You can be right and still be gentle. Choose the answer that builds."],
  ["Carry the Weight", "Carry each other's burdens, and in this way you will fulfill the law of Christ.", "Galatians 6:2", "Strength is not carrying everything alone. It is stepping under someone else's weight."],
  ["Encourage", "Therefore encourage one another and build each other up.", "1 Thessalonians 5:11", "Someone near you is one word away from giving up. Be the word that keeps them in."],
  ["Quick to Listen", "Everyone should be quick to listen, slow to speak and slow to become angry.", "James 1:19", "Most conflict shrinks when one person decides to listen first."],
  ["Pursue Peace", "Make every effort to live in peace with everyone.", "Hebrews 12:14", "Peace is not passive. It takes effort. Make the effort today."],
  ["Unfailing Love", "Because your love is better than life, my lips will glorify you.", "Psalm 63:3", "His love does not run dry or run out. Let it be enough today."],
  ["Rooted in Love", "Being rooted and established in love.", "Ephesians 3:17", "When you are rooted in His love, criticism cannot uproot you."],
  ["No Fear in Love", "There is no fear in love. But perfect love drives out fear.", "1 John 4:18", "You do not have to earn it or fear losing it. His love is settled."],
  ["Serve One Another", "Serve one another humbly in love.", "Galatians 5:13", "Freedom is not for selfishness. It is the freedom to serve. Use it."],
  ["Comfort Others", "Comfort those in any trouble with the comfort we ourselves receive from God.", "2 Corinthians 1:4", "What you have walked through can help someone else walk through theirs."],
  ["Speak the Truth", "Speaking the truth in love, we will grow.", "Ephesians 4:15", "Truth without love wounds. Love without truth flatters. Hold both."],
  ["Honor Your Word", "Let your yes be yes, and your no be no.", "Matthew 5:37", "Your word is your weight. People should be able to build on it."],
  ["Slow to Anger", "Whoever is slow to anger has great understanding.", "Proverbs 14:29", "A short fuse burns the people closest to you. Lengthen it today."],
  ["Set an Example", "Set an example for the believers in speech, in conduct, in love, in faith.", "1 Timothy 4:12", "You lead more by how you live than by what you say."],
  ["Faithful in Little", "Whoever can be trusted with very little can also be trusted with much.", "Luke 16:10", "Big trust is built in small faithfulness. Be faithful where you are."],
  ["The Greatest", "Whoever wants to become great among you must be your servant.", "Mark 10:43", "Real strength bends low. Serve someone today and call it greatness."],
  ["Clothe Yourself", "Clothe yourselves with compassion, kindness, humility, gentleness and patience.", "Colossians 3:12", "These are not weaknesses. They are what strength wears."],
  ["Do Not Grow Weary", "Let us not become weary in doing good.", "Galatians 6:9", "The good you do unseen still counts. Keep doing it."],
  ["Husband and Wife", "Submit to one another out of reverence for Christ.", "Ephesians 5:21", "A strong home is built on mutual honor, not on winning."],
  ["Train the Heart", "As water reflects the face, so one's life reflects the heart.", "Proverbs 27:19", "What is in you will show up in your life. Tend the inside."],

  // ── MARCH ──
  ["The Harvest Later", "No discipline seems pleasant at the time, but painful. Later it produces a harvest.", "Hebrews 12:11", "The work you avoid today is the harvest you will want tomorrow."],
  ["Discipline the Body", "I strike a blow to my body and make it my slave.", "1 Corinthians 9:27", "Your body serves your purpose, not the other way around. Take the reins."],
  ["Press Toward", "I press on toward the goal to win the prize.", "Philippians 3:14", "Aim at something worth the strain. Then press."],
  ["Sow and Reap", "A man reaps what he sows.", "Galatians 6:7", "Today is seed. Plant what you actually want to harvest."],
  ["Be Diligent", "The plans of the diligent lead to profit as surely as haste leads to poverty.", "Proverbs 21:5", "Steady beats frantic. Do the next right thing well."],
  ["Finish the Race", "I have fought the good fight, I have finished the race, I have kept the faith.", "2 Timothy 4:7", "Starting is easy. Finishing is faithfulness. Do not quit early."],
  ["Train for Godliness", "Physical training is of some value, but godliness has value for all things.", "1 Timothy 4:8", "Train the body. Train the soul harder. One outlasts the other."],
  ["Numbered Days", "Teach us to number our days, that we may gain a heart of wisdom.", "Psalm 90:12", "You do not get this day back. Spend it like it counts, because it does."],
  ["Stand Firm", "Be on your guard; stand firm in the faith; be courageous; be strong.", "1 Corinthians 16:13", "Four commands, one stance: do not move off the truth."],
  ["Run to Win", "Run in such a way as to get the prize.", "1 Corinthians 9:24", "Going through the motions is not running. Run like it matters."],
  ["Consistency", "The integrity of the upright guides them.", "Proverbs 11:3", "Who you are when no one watches is who you actually are. Be consistent."],
  ["Self-Control", "Like a city whose walls are broken through is a person who lacks self-control.", "Proverbs 25:28", "Without walls, anything gets in. Self-control is the wall. Build it."],
  ["Hard Work", "All hard work brings a profit, but mere talk leads only to poverty.", "Proverbs 14:23", "Stop announcing what you will do. Go do it."],
  ["Whatever You Do", "Whatever you do, work at it with all your heart, as working for the Lord.", "Colossians 3:23", "The job is an offering when you do it for Him. Give it everything."],
  ["Endurance", "Let perseverance finish its work so that you may be mature and complete.", "James 1:4", "Do not pray only for the trial to end. Let it finish what it is building."],
  ["Sharpened", "As iron sharpens iron, so one person sharpens another.", "Proverbs 27:17", "You were not made to grow alone. Who is sharpening you?"],
  ["Refined", "He will sit as a refiner and purifier of silver.", "Malachi 3:3", "The fire is not against you. It is removing what is not you."],
  ["Keep Watch", "Watch and pray so that you will not fall into temptation.", "Matthew 26:41", "Temptation hunts the unguarded. Stay awake."],
  ["Do Not Conform", "Do not conform to the pattern of this world.", "Romans 12:2", "Everyone drifting the same direction does not make it the right one."],
  ["Strength for Today", "As your days, so shall your strength be.", "Deuteronomy 33:25", "He does not give tomorrow's strength today. He gives enough for now."],
  ["Take Up", "Whoever wants to be my disciple must deny themselves and take up their cross daily.", "Luke 9:23", "Following Him is a daily decision, not a one-time feeling."],
  ["Be Sober-Minded", "Be alert and of sober mind.", "1 Peter 5:8", "Readiness is not paranoia. It is responsibility. Stay clear-headed."],
  ["Fix Your Eyes", "Fixing our eyes on Jesus, the pioneer and perfecter of faith.", "Hebrews 12:2", "You move toward what you look at. Keep your eyes on Him."],
  ["The Word in You", "I have hidden your word in my heart that I might not sin against you.", "Psalm 119:11", "What you store inside is what holds when pressure comes. Store the Word."],
  ["Be Faithful", "Be faithful, even to the point of death, and I will give you the crown of life.", "Revelation 2:10", "Faithfulness is not flashy. It is just not quitting. Keep going."],
  ["Disciplined Tongue", "Those who consider their ways keep their tongues from evil.", "Psalm 34:13", "Master the mouth and you are most of the way to mastering yourself."],
  ["Stay the Course", "Let us hold unswervingly to the hope we profess.", "Hebrews 10:23", "Do not negotiate your convictions when it gets uncomfortable. Hold."],
  ["Work Heartily", "Whatever your hand finds to do, do it with all your might.", "Ecclesiastes 9:10", "Half-effort is a slow leak. Pour yourself into what is in front of you."],
  ["Rooted Deep", "Like a tree planted by streams of water, which yields its fruit in season.", "Psalm 1:3", "Stay rooted near the source and the fruit comes in time."],
  ["Train Up", "Start children off on the way they should go.", "Proverbs 22:6", "Someone is watching how you handle today. Give them something worth imitating."],
  ["Strength Renewed", "He gives strength to the weary and increases the power of the weak.", "Isaiah 40:29", "Weakness is not the end of the story. It is where His power starts."],

  // ── APRIL ──
  ["He Is Risen", "He is not here; he has risen, just as he said.", "Matthew 28:6", "The grave could not hold Him, and it will not hold you. Live like it."],
  ["New Life", "We too may live a new life.", "Romans 6:4", "Resurrection is not just history. It is the power available to you now."],
  ["Living Hope", "He has given us new birth into a living hope through the resurrection.", "1 Peter 1:3", "Your hope is not wishful thinking. It is anchored in an empty tomb."],
  ["Death Defeated", "Where, O death, is your victory? Where, O death, is your sting?", "1 Corinthians 15:55", "The worst thing is no longer the last thing. Fear loses its grip."],
  ["Buried and Raised", "If we have been united with him in a death like his, we will be united with him in his resurrection.", "Romans 6:5", "What died with Him stays dead. What rose with Him is your new life."],
  ["Springs Up", "Now is the time of God's favor.", "2 Corinthians 6:2", "Not someday. Now. He is at work in this season, not just the next."],
  ["Everything New", "Behold, I am making all things new.", "Revelation 21:5", "Nothing is too far gone for the One who makes all things new."],
  ["Alive Together", "Made us alive with Christ even when we were dead in transgressions.", "Ephesians 2:5", "You did not earn this life. He gave it while you were unable. Receive it."],
  ["The Stone Rolled", "They found the stone rolled away from the tomb.", "Luke 24:2", "What you thought was sealed shut, He can open. Do not count it final."],
  ["Hope Does Not Disappoint", "And hope does not put us to shame.", "Romans 5:5", "Hope in Him is never wasted. Keep hoping out loud."],
  ["First Fruits", "Christ has indeed been raised from the dead, the firstfruits.", "1 Corinthians 15:20", "His resurrection is the promise of yours. The first of many."],
  ["Look Up", "Set your minds on things above, not on earthly things.", "Colossians 3:2", "What you fix your mind on shapes your day. Aim it higher."],
  ["He Lives", "Because I live, you also will live.", "John 14:19", "Your life is tied to His, and His cannot be ended. That is your security."],
  ["Mercy New", "His compassions never fail. They are new every morning.", "Lamentations 3:22-23", "Yesterday's failures do not get a vote today. Mercy reset overnight."],
  ["Restored", "I will restore to you the years the locusts have eaten.", "Joel 2:25", "What was lost is not beyond His reach. He restores."],
  ["Rejoice Always", "Rejoice in the Lord always. I will say it again: Rejoice!", "Philippians 4:4", "Joy is not denial. It is choosing to anchor in Him regardless of the weather."],
  ["Streams in the Desert", "I am making a way in the wilderness and streams in the wasteland.", "Isaiah 43:19", "He specializes in roads where there were none. Watch for the way."],
  ["Lifted Up", "He lifted me out of the slimy pit; he set my feet on a rock.", "Psalm 40:2", "He does not just rescue. He gives you solid ground to stand on."],
  ["Garment of Praise", "A crown of beauty instead of ashes, the oil of joy instead of mourning.", "Isaiah 61:3", "He trades your ashes for beauty. Bring Him what is burned."],
  ["Morning Comes", "Weeping may stay for the night, but rejoicing comes in the morning.", "Psalm 30:5", "The night is real, but it is not permanent. Morning is coming."],
  ["Be Renewed", "Though outwardly we are wasting away, yet inwardly we are being renewed day by day.", "2 Corinthians 4:16", "The outside fades. The inside, in Him, grows stronger daily."],
  ["Strength to Stand", "The joy of the Lord is your strength.", "Nehemiah 8:10", "Joy is not the reward for strength. It is the source of it."],
  ["Fruit in Season", "The fruit of the Spirit is love, joy, peace, patience, kindness.", "Galatians 5:22", "You cannot force fruit. You stay connected and it grows."],
  ["Pruned to Grow", "Every branch that does bear fruit he prunes so that it will be even more fruitful.", "John 15:2", "The cutting is not punishment. It is investment in more."],
  ["Abide", "Remain in me, as I also remain in you.", "John 15:4", "Apart from Him you produce nothing that lasts. Stay close."],
  ["Living Water", "Whoever drinks the water I give them will never thirst.", "John 4:14", "The world's wells run dry. His does not. Drink from the right source."],
  ["Be Glad", "This is the day the Lord has made; let us rejoice and be glad in it.", "Psalm 118:24", "He made today on purpose. Do not waste it wishing for another."],
  ["Cleansed", "Though your sins are like scarlet, they shall be as white as snow.", "Isaiah 1:18", "He does not just cover the stain. He removes it. You are clean."],
  ["Sing", "Sing to the Lord a new song.", "Psalm 96:1", "Old grief does not need today's soundtrack. Sing something new."],
  ["Held Fast", "I will never leave you nor forsake you.", "Hebrews 13:5", "He is not going anywhere. That is the ground you stand on."],

  // ── MAY ──
  ["Honor Father and Mother", "Honor your father and your mother.", "Exodus 20:12", "Gratitude starts at home. Honor the ones who got you here."],
  ["A Mother's Strength", "She is clothed with strength and dignity; she can laugh at the days to come.", "Proverbs 31:25", "Strength wears many faces. Today, see it in the women who never quit."],
  ["Children a Gift", "Children are a heritage from the Lord, offspring a reward from him.", "Psalm 127:3", "The people in your home are not interruptions. They are the assignment."],
  ["Build the House", "Unless the Lord builds the house, the builders labor in vain.", "Psalm 127:1", "Work hard on your home, but let Him be the architect."],
  ["As for My House", "As for me and my household, we will serve the Lord.", "Joshua 24:15", "Decide for your home before the culture decides for you."],
  ["Teach Diligently", "Impress them on your children. Talk about them when you sit at home.", "Deuteronomy 6:7", "Faith is passed in the ordinary moments. Use them."],
  ["A Good Name", "A good name is more desirable than great riches.", "Proverbs 22:1", "Build a name your kids are proud to carry. That outlasts money."],
  ["Provide", "Anyone who does not provide for their household has denied the faith.", "1 Timothy 5:8", "Provision is a calling, not a burden. Show up for your people."],
  ["Bring Them Up", "Bring them up in the training and instruction of the Lord.", "Ephesians 6:4", "Discipline without warmth crushes. Lead your home with both."],
  ["Crown of the Aged", "Children's children are a crown to the aged.", "Proverbs 17:6", "Legacy is generational. What you build now blesses people you may never meet."],
  ["Faith of Generations", "I am reminded of your sincere faith, which first lived in your grandmother and your mother.", "2 Timothy 1:5", "Faith handed down is one of the greatest gifts you can give. Pass it on."],
  ["Love Your Wife", "Husbands, love your wives, just as Christ loved the church.", "Ephesians 5:25", "Sacrificial love is the standard. Lay something down for her today."],
  ["A Wise Builder", "The wise woman builds her house.", "Proverbs 14:1", "Every word and choice either builds or tears down the home. Build."],
  ["Peace at Home", "If it is possible, as far as it depends on you, live at peace with everyone.", "Romans 12:18", "You cannot control everyone, but you can be the calm in your house."],
  ["Children Listen", "Listen, my son, to your father's instruction.", "Proverbs 1:8", "What you say matters because someone small is taking notes."],
  ["Generous Home", "A generous person will prosper; whoever refreshes others will be refreshed.", "Proverbs 11:25", "Make your home a place that pours out, and watch it get filled."],
  ["Forgive at Home", "Be kind and compassionate to one another, forgiving each other.", "Ephesians 4:32", "The hardest place to forgive is home. Do it there first."],
  ["Cord of Three", "A cord of three strands is not quickly broken.", "Ecclesiastes 4:12", "Two are stronger than one. Two with God are unbreakable."],
  ["Words That Build", "Do not let any unwholesome talk come out of your mouths, but only what builds up.", "Ephesians 4:29", "Your family hears your tone before your words. Make both build."],
  ["A Refuge", "God sets the lonely in families.", "Psalm 68:6", "Family is one of His answers to loneliness. Be that for someone."],
  ["Lead Gently", "A bruised reed he will not break.", "Matthew 12:20", "Strength that crushes the weak is not strength. Lead gently."],
  ["Patient Love", "Love does not envy, it does not boast, it is not proud.", "1 Corinthians 13:4", "The people who know you best deserve your most patient self."],
  ["Stay Faithful", "Rejoice in the wife of your youth.", "Proverbs 5:18", "Faithfulness is a daily choice that protects everything you are building."],
  ["Serve Your Family", "Through love serve one another.", "Galatians 5:13", "Leadership at home looks like a towel, not a throne."],
  ["A Father's Compassion", "As a father has compassion on his children, so the Lord has compassion.", "Psalm 103:13", "However you father, the Father fathers better. Lean into His example."],
  ["Train the Heart", "Above all else, guard your heart.", "Proverbs 4:23", "Guard your own heart so you can help guard theirs."],
  ["Worth More", "You are worth more than many sparrows.", "Matthew 10:31", "Remind the people you love how seen and valued they are."],
  ["Hospitality", "Share with the Lord's people who are in need. Practice hospitality.", "Romans 12:13", "Open your table. The kingdom often advances over a meal."],
  ["Be the Calm", "A heart at peace gives life to the body.", "Proverbs 14:30", "Your peace sets the temperature of your home. Bring His peace in."],
  ["Bless Them", "The Lord bless you and keep you.", "Numbers 6:24", "Speak blessing over your people out loud. Words shape lives."],
  ["Stand Together", "Two are better than one, because they have a good return for their labor.", "Ecclesiastes 4:9", "You were not built to do life solo. Stand with someone."],

  // ── JUNE ──
  ["Be a Man of Courage", "Be on your guard; stand firm in the faith; be courageous; be strong.", "1 Corinthians 16:13", "Courage isn't a feeling you wait for — it's a decision you make before the moment ever arrives. The man who settles ahead of time how he'll respond doesn't crumble when the pressure hits. Decide now, in the quiet, so you can stand later in the storm."],
  ["Quiet Strength", "In quietness and trust is your strength.", "Isaiah 30:15", "Loud is not the same as strong. The strongest men you know are usually the steadiest — unhurried, unshaken, sure of who holds them. Your strength today won't come from noise or hustle, but from quiet trust in God."],
  ["Lead by Serving", "The greatest among you will be your servant.", "Matthew 23:11", "The world says leadership is about being served; Jesus flipped it on its head. Want to lead? Pick up what everyone else walks past. Serve the people no one is watching you serve, and you'll become the kind of man others actually want to follow."],
  ["Steady Hands", "Commit to the Lord whatever you do, and he will establish your plans.", "Proverbs 16:3", "You can grip your plans so tightly that your own hands start to shake. Commit the work to God instead — hand Him the outcome you were never able to control anyway. He steadies what you surrender."],
  ["A Father Provides", "Look at the birds of the air; they do not sow or reap or store away in barns, and yet your heavenly Father feeds them.", "Matthew 6:26", "He feeds sparrows that never lie awake worrying about tomorrow. If He watches over the birds, He hasn't forgotten your house, your bills, or your kids. Provision is His job; faithfulness is yours."],
  ["Strong and Tender", "Be completely humble and gentle; be patient, bearing with one another.", "Ephesians 4:2", "Strength that can't be gentle isn't strength — it's just force. Real power chooses patience, holds its tongue, and bears with people on their worst days. Be strong enough to be tender on purpose."],
  ["Stand in the Gap", "I looked for someone among them who would stand in the gap.", "Ezekiel 22:30", "God still looks for the one willing to step into the gap everyone else avoids — the hard conversation, the prayer nobody's praying, the person nobody's helping. Be that one today. The gap is where leaders are made."],
  ["Faithful Provider", "She watches over the affairs of her household and does not eat the bread of idleness.", "Proverbs 31:27", "Diligence is just love in work clothes. Watching over your people — showing up, following through, doing the unseen work — is one of the loudest ways to say 'I've got you.' Don't coast on yesterday; earn your rest today."],
  ["No Fear", "God has not given us a spirit of fear, but of power, love and a sound mind.", "2 Timothy 1:7", "Fear is a liar with a loud voice. God never handed you a spirit of fear — He gave you power, love, and a sound mind. When the lie gets loud, name what's actually yours and walk in it anyway."],
  ["The Lord My Rock", "The Lord is my rock, my fortress and my deliverer.", "Psalm 18:2", "Build your life on the Rock and the storms can come as hard as they want — you will not fall. Sand looks just fine until the rain hits. Ask yourself honestly: what am I building on today?"],
  ["Lead Yourself First", "Better a patient person than a warrior, one with self-control than one who takes a city.", "Proverbs 16:32", "Before you can lead a family, a team, or a room, you have to lead yourself. Self-control is a quieter victory than conquering a city, but Scripture calls it the greater one. Master your own response before you try to manage anyone else's."],
  ["Daily Bread", "Give us today our daily bread.", "Matthew 6:11", "He gives you enough for today — not a stockpile, a supply. That's on purpose; it keeps you coming back to Him instead of to your savings. Take what He provides for today and trust Him again tomorrow."],
  ["Stand Firm Together", "Conduct yourselves in a manner worthy of the gospel of Christ, standing firm in the one Spirit, striving together as one for the faith of the gospel.", "Philippians 1:27", "Brotherhood isn't a hobby you pick up when it's convenient. It's a stand you take together, shoulder to shoulder, especially when it costs you something. Who are you actually standing firm with right now?"],
  ["Strength to the Weary", "He gives strength to the weary.", "Isaiah 40:29", "Tired is not the same as disqualified. God specializes in the weary and the worn-out — the empty tank is exactly where His strength tends to show up. Bring Him your exhaustion instead of hiding it behind a strong face."],
  ["Be Vigilant", "Keep your servant from willful sins; may they not rule over me.", "Psalm 19:13", "Nobody falls all at once; it's the small compromises that quietly start running a man before he even notices. Guard the little hinge decisions and the big doors stay shut. Stay watchful where you think you're strongest."],
  ["A Man of His Word", "Let your yes be yes.", "Matthew 5:37", "Your word is your weight — what you say should be something people can build on. When you commit, follow through, even when it's inconvenient and even when no one's checking. Let your yes mean yes long after the feeling fades."],
  ["Fight the Good Fight", "Fight the good fight of the faith.", "1 Timothy 6:12", "Not every fight is yours to pick — but this one, the fight of faith, is. Stop bleeding your strength on battles that don't matter and engage the one that does. Contend for your faith like it's worth contending for, because it is."],
  ["Renew My Spirit", "Create in me a pure heart, O God, and renew a steadfast spirit within me.", "Psalm 51:10", "When you blow it — and you will — don't run and hide. David didn't just ask to feel better; he asked God to create something clean in him. Come honest, and let Him renew what you broke."],
  ["Stand for Truth", "Buy the truth and do not sell it.", "Proverbs 23:23", "Truth is expensive to hold and cheap to abandon — which is exactly why so few people hold it. Pay the price for it anyway, and once you've got it, don't sell it for comfort, approval, or an easier life. Some things are worth more than being liked."],
  ["Strength Made Perfect", "My power is made perfect in weakness.", "2 Corinthians 12:9", "Your limits aren't a problem for God to apologize for — they're the room His power moves into. The place you feel weakest is often exactly where He wants to show up strongest. Stop hiding the cracks; that's where the light gets in."],
  ["Walk Humbly", "Act justly, love mercy and walk humbly with your God.", "Micah 6:8", "Act justly, love mercy, walk humbly — three marks of a real man of God, and not one of them is flashy. You don't have to be loud to be righteous; you have to be faithful. Live these three out today, where no one's filming."],
  ["Be Strong in Grace", "Be strong in the grace that is in Christ Jesus.", "2 Timothy 2:1", "Willpower runs out — grace doesn't. Your strength was never supposed to come from gritting your teeth harder; it's fueled by the grace already yours in Christ. Stop white-knuckling your faith and start drawing from the well that won't run dry."],
  ["A Legacy", "A good person leaves an inheritance for their children's children.", "Proverbs 13:22", "Think past today and past yourself. A good man builds something that outlives him — not just money, but faith, character, and a name his grandkids are proud to carry. What you do this year, your line could feel for generations."],
  ["Endure Hardship", "Endure hardship with us like a good soldier of Christ Jesus.", "2 Timothy 2:3", "Comfort was never the goal — faithfulness under load is. A good soldier doesn't quit when it gets heavy; he leans in and carries it. The weight you're under isn't proof you're failing — it may be proof you're being forged."],
  ["Trust His Timing", "He has made everything beautiful in its time.", "Ecclesiastes 3:11", "You are not behind. He makes everything beautiful in its time, and His timeline runs deeper than the one you can see from here. Keep doing the next right thing and let Him handle the clock."],
  ["Be Watchful", "Therefore keep watch, because you do not know the day.", "Matthew 24:42", "Live ready. The watchful man isn't anxious — he's prepared, so nothing catches him flat-footed. Stay awake to what God is doing and to how you're living, because you don't get to know the day."],
  ["Strength in Numbers", "Where two or three gather in my name, there am I with them.", "Matthew 18:20", "Isolation is where the enemy does his best work, so don't go it alone. Jesus promises to show up where His people gather, even if it's just two or three. Get in the room with your brothers and sisters — that's where He meets you."],
  ["Set Your Mind", "Be transformed by the renewing of your mind.", "Romans 12:2", "The battle is won or lost in your mind long before it ever shows up in your life. Renew it daily — feed it truth, starve it of lies — and your actions will follow where your thoughts lead. Don't let the world quietly set your default settings."],
  ["The Father's Heart", "How great is the love the Father has lavished on us, that we should be called children of God.", "1 John 3:1", "You are not just His servant grinding for approval — you are His child, already loved. Lead, serve, and fight from that settled identity, not for it. Everything changes the day you stop trying to earn what you've already been given."],
  ["Run Your Race", "Each of us will give an account of ourselves to God.", "Romans 14:12", "Stop staring at the next man's lane — comparison will rob you of your whole race. You'll give an account for yours, not his. Run the race God marked out for you, at the pace He set, all the way to the line."],

  // ── JULY ──
  ["True Freedom", "It is for freedom that Christ has set us free. Stand firm, then, and do not let yourselves be burdened again by a yoke of slavery.", "Galatians 5:1", "You weren't set free to drift; you were set free to stand. Freedom isn't the absence of a fight — it's the strength to plant your feet and refuse to get dragged back into what used to own you. Whatever Christ broke you out of, don't go wandering back toward the chains."],
  ["Free Indeed", "So if the Son sets you free, you will be free indeed.", "John 8:36", "Real freedom was never mostly about your circumstances — it's about the chains He breaks on the inside. A man can be free on paper and still be a prisoner in his own head. Let the Son free the part of you that no situation ever could."],
  ["Liberty and Restraint", "Live as free people, but do not use your freedom as a cover-up for evil; live as God's slaves.", "1 Peter 2:16", "Freedom without responsibility isn't freedom — it's just a nicer-looking cage. The point of being set free was never to do whatever you want; it was to finally be able to do what's right. Don't use grace as an excuse to feed what God died to kill."],
  ["Where the Spirit Is", "Now the Lord is the Spirit, and where the Spirit of the Lord is, there is freedom.", "2 Corinthians 3:17", "Freedom isn't a place you arrive at; it's a Presence you stay near. The chains tend to fall right where the Spirit is moving, which is why drifting from Him always feels heavier. Stay close, and freedom comes with the company."],
  ["Stand Firm in Freedom", "Stand firm, then, and do not let yourselves be burdened again by a yoke of slavery.", "Galatians 5:1", "He didn't break those chains so you could pick them back up on a hard day. The same habit, the same fear, the same lie — you were freed from that on purpose. Stand firm, and stop reaching for the yoke He already lifted off your neck."],
  ["Courage to Stand", "Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", "Joshua 1:9", "Freedom is always defended by the courageous, never the comfortable. God doesn't tell Joshua to feel brave; He commands it, then backs it with His own presence. Be strong because He goes with you, not because the odds look good."],
  ["A Nation Under God", "Blessed is the nation whose God is the Lord, the people he chose for his inheritance.", "Psalm 33:12", "Pray for your country instead of just complaining about it. A nation rises or falls on whether its people actually know the One who blesses it — and that starts with households like yours. Live in a way today that makes your corner of it better."],
  ["Light to the Nations", "You are the light of the world. A town built on a hill cannot be hidden.", "Matthew 5:14", "You don't fix a dark country with one big switch; you fix it one life shining at a time. You are the light right where you stand — your job, your street, your group chat. Don't hide it under fear or the need to fit in."],
  ["Pursue Righteousness", "Righteousness exalts a nation, but sin is a disgrace to any people.", "Proverbs 14:34", "What you do quietly shapes the culture loudly. Nations don't drift on the big decisions; they drift on a million small private ones, including yours. Choose right when no one is watching and you're already changing the country."],
  ["Pray for Leaders", "I urge that petitions, prayers, intercession and thanksgiving be made for all people — for kings and all those in authority, that we may live peaceful and quiet lives.", "1 Timothy 2:1-2", "Pray for your leaders before you pick them apart — it'll change you as much as it changes them. It's hard to despise a man you're genuinely lifting before God. Intercede first; critique second."],
  ["Truth Sets Free", "Then you will know the truth, and the truth will set you free.", "John 8:32", "Half-truths keep you comfortable and bound at the same time. Freedom doesn't come from the version of the story that protects your ego; it comes from the whole truth, even when it stings. Walk in all of it and watch the chains loosen."],
  ["Be Bold", "The wicked flee though no one pursues, but the righteous are as bold as a lion.", "Proverbs 28:1", "When you've got nothing to hide, you've got nothing to fear. A clear conscience is its own kind of courage — it lets you walk into any room standing up straight. Live so clean that boldness just comes naturally."],
  ["Stand Your Ground", "Therefore put on the full armor of God, so that when the day of evil comes, you may be able to stand your ground, and after you have done everything, to stand.", "Ephesians 6:13", "Sometimes faithfulness isn't advancing — it's just refusing to fall back. There are seasons where 'still standing' is the whole victory. When you've done everything you know to do, do the last thing: stand."],
  ["Freedom to Serve", "You, my brothers and sisters, were called to be free. But do not use your freedom to indulge the flesh; rather, serve one another humbly in love.", "Galatians 5:13", "The best thing you can do with your freedom is spend it on someone else. Liberty that only ever serves yourself curdles fast into selfishness. Take what He gave you and pour it out — that's freedom doing what it was made for."],
  ["Strength and Honor", "She is clothed with strength and dignity; she can laugh at the days to come.", "Proverbs 31:25", "Let strength and honor be the things people sense on you before you ever say a word. A life clothed that way isn't anxious about the future — it can laugh at the days to come because of who holds them. Wear it daily."],
  ["Stand in Faith", "For we live by faith, not by sight.", "2 Corinthians 5:7", "Freedom usually means walking forward before you can actually see the path. Sight wants the whole map before the first step; faith takes the step and trusts the One who drew the map. Move on what He said, not on what you can see."],
  ["Be Courageous", "Wait for the Lord; be strong and take heart and wait for the Lord.", "Psalm 27:14", "Sometimes courage doesn't look like charging — it looks like waiting without backing down. Holding your post when everything in you wants to bolt is its own kind of brave. Be strong, take heart, and wait on Him."],
  ["Overcome", "I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.", "John 16:33", "He never promised a life without trouble; He promised peace right in the middle of it. The war is already decided — He has overcome the world. So you fight from victory, not for it."],
  ["No Chains", "This is my gospel, for which I am suffering even to the point of being chained like a criminal. But God's word is not chained.", "2 Timothy 2:9", "Your circumstances can bind you, but they cannot bind what God is doing through you. Paul wrote some of his most powerful words from a prison cell. Whatever's holding you back right now, it can't hold back His Word in you."],
  ["Liberty Within", "I run in the path of your commands, for you have broadened my understanding.", "Psalm 119:32", "God's commands aren't a fence built to shrink your life; they're the open road built to free it. What the world calls restriction, the man who's tasted it calls relief. Run that path and feel how wide it actually is."],
  ["Stand for the Weak", "Defend the weak and the fatherless; uphold the cause of the poor and the oppressed.", "Psalm 82:3", "Use your freedom and your strength to lift the people who have neither. Real strength always bends down toward the overlooked — the kid with no dad, the family barely making it. Spend some of your margin on them today."],
  ["A Firm Foundation", "Nevertheless, God's solid foundation stands firm, sealed with this inscription: 'The Lord knows those who are his.'", "2 Timothy 2:19", "Everything you can name will shake eventually — except what He builds. When the ground moves under your plans, your job, or your health, His foundation holds. Stand on the thing that cannot be shaken."],
  ["Press On in Freedom", "I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus.", "Philippians 3:14", "Freedom isn't a finish line you cross and then coast; it's a direction you keep pressing. There's always more ground ahead that He's called you toward. Don't camp on yesterday's breakthrough — press on."],
  ["Be the Salt", "You are the salt of the earth. But if the salt loses its saltiness, how can it be made salty again?", "Matthew 5:13", "Salt does two things: it preserves what's good and it brings out flavor. You're meant to be both in every room you walk into. Don't blend in so well that you lose the very thing that made you useful."],
  ["Unshaken", "They will have no fear of bad news; their hearts are steadfast, trusting in the Lord. Their hearts are secure, they will have no fear.", "Psalm 112:7-8", "A heart anchored in God doesn't panic every time the news does. Steadiness isn't pretending nothing's wrong; it's trusting Someone bigger than what's wrong. Let your security come from Him and watch how little can rattle you."],
  ["Choose This Day", "Choose for yourselves this day whom you will serve. But as for me and my household, we will serve the Lord.", "Joshua 24:15", "Freedom includes the freedom to choose, and that choice gets made fresh every single day. You don't drift into serving God; you decide it, and then you decide it again tomorrow. Lead your household by choosing well today."],
  ["Strong to the End", "He will also keep you firm to the end, so that you will be blameless on the day of our Lord Jesus Christ.", "1 Corinthians 1:8", "He doesn't set you free and then leave you to white-knuckle it alone. The same God who broke the chains commits to keeping you standing all the way to the finish. He's not just your rescuer; He's your sustainer."],
  ["Walk in Step", "Since we live by the Spirit, let us keep in step with the Spirit.", "Galatians 5:25", "Freedom was never permission to do whatever you feel like — it's the ability to finally keep pace with the Spirit. Marching to your own drum looks like liberty and ends in a ditch. Match His steps and you'll end up somewhere good."],
  ["Courage in the Fire", "If we are thrown into the blazing furnace, the God we serve is able to deliver us from it. But even if he does not, we want you to know that we will not serve your gods.", "Daniel 3:17-18", "Real faith stands whether or not it gets the rescue it asked for. Those three men trusted God to deliver them — and trusted Him even if He didn't. Settle that 'but even if He does not' in your heart now, and the fire loses its grip on you."],
  ["Set Free to Stand", "It was for freedom that Christ set us free; stand firm, then, and do not let yourselves be burdened again by a yoke of slavery.", "Galatians 5:1", "He set you free for a reason, not for nothing — so don't waste it standing still or slipping back. Freedom that isn't used to stand for something quietly drains away. Plant your feet on what He bought for you."],
  ["Liberty in Christ", "Now the Lord is the Spirit, and where the Spirit of the Lord is, there is freedom.", "2 Corinthians 3:17", "When you carry His presence, you carry freedom into every room you enter. You stop needing the situation to be perfect because the thing that frees you lives inside you. Walk in today knowing you bring the freedom with you."],

  // ── AUGUST ──
  ["Do Not Grow Weary", "Let us not become weary in doing good, for at the proper time we will reap a harvest.", "Galatians 6:9", "The middle is where most quit. Do not. The harvest is real."],
  ["Strength for the Journey", "They go from strength to strength.", "Psalm 84:7", "You do not have to feel strong to keep moving. Step toward the next strength."],
  ["Persevere", "Blessed is the one who perseveres under trial.", "James 1:12", "The trial is training, not punishment. Endure it, do not waste it."],
  ["Keep Going", "Let us run with perseverance the race marked out for us.", "Hebrews 12:1", "Tired is not a reason to stop. It is a reason to lean on Him and continue."],
  ["Work as Worship", "Whatever you do, work at it with all your heart.", "Colossians 3:23", "Ordinary work done for Him becomes worship. Give it your best."],
  ["Sustained", "Cast your cares on the Lord and he will sustain you.", "Psalm 55:22", "He does not just hear the weight. He carries it. Hand it over."],
  ["Plodding Wins", "The plans of the diligent lead to profit.", "Proverbs 21:5", "Steady, unglamorous effort beats bursts of motivation. Plod on."],
  ["Mounting Up", "They will soar on wings like eagles; they will run and not grow weary.", "Isaiah 40:31", "Hope in Him is the updraft. Wait for it, then rise."],
  ["Faithful in the Field", "The hardworking farmer should be the first to receive a share of the crops.", "2 Timothy 2:6", "Do the work first. The reward follows the labor."],
  ["Strength Within", "I pray that he may strengthen you with power through his Spirit in your inner being.", "Ephesians 3:16", "Real strength is built on the inside where no one sees."],
  ["Stay the Course", "Let us hold unswervingly to the hope we profess, for he who promised is faithful.", "Hebrews 10:23", "Hold on because He is holding on to you. He is faithful."],
  ["Endurance Produces", "Suffering produces perseverance; perseverance, character; and character, hope.", "Romans 5:3-4", "The hard season is making you, not breaking you. Let it work."],
  ["Wait Well", "Wait for the Lord; be strong and take heart and wait for the Lord.", "Psalm 27:14", "Waiting is not wasting. Strength is built in the wait."],
  ["Carry On", "I have learned to be content whatever the circumstances.", "Philippians 4:11", "Contentment is a skill, not a circumstance. Practice it today."],
  ["Strong Hands", "Strengthen the feeble hands, steady the knees that give way.", "Isaiah 35:3", "If you are steady today, steady someone else. We finish together."],
  ["The Long Obedience", "We are confident, I say, and would prefer to be... pleasing to him.", "2 Corinthians 5:8-9", "Aim to please Him over the long haul, not just the moment."],
  ["He Carries You", "He tends his flock like a shepherd: He gathers the lambs in his arms.", "Isaiah 40:11", "When you cannot walk, He carries. You are not abandoned."],
  ["Be Steadfast", "Always abounding in the work of the Lord, because your labor is not in vain.", "1 Corinthians 15:58", "Nothing done for Him is wasted. Keep pouring it out."],
  ["Do Not Give Up", "We do not lose heart.", "2 Corinthians 4:1", "Losing heart is optional. Choose not to today."],
  ["Refuge in Trouble", "God is our refuge and strength, an ever-present help in trouble.", "Psalm 46:1", "He is not far off in the storm. He is present help, right now."],
  ["Faithful Steward", "Well done, good and faithful servant.", "Matthew 25:21", "Live for the day you hear those words. Be faithful with what you hold."],
  ["Strength in Stillness", "The Lord will fight for you; you need only to be still.", "Exodus 14:14", "Sometimes the strongest move is to stop striving and trust."],
  ["Press Through", "Forgetting what is behind and straining toward what is ahead.", "Philippians 3:13", "Stop replaying yesterday. Strain toward what He has ahead."],
  ["Be Strong and Work", "Be strong... and work. For I am with you, declares the Lord.", "Haggai 2:4", "His presence is the reason to keep working. He is with you."],
  ["Hold the Line", "Stand firm. Let nothing move you.", "1 Corinthians 15:58", "When pressure pushes, plant your feet. Hold the line."],
  ["Grace Sufficient", "My grace is sufficient for you.", "2 Corinthians 12:9", "You do not need more willpower. You need His grace, and you have it."],
  ["Run to Finish", "I have finished the race, I have kept the faith.", "2 Timothy 4:7", "Picture the finish. Live today in a way you will be proud of there."],
  ["Strength Renewed Daily", "Inwardly we are being renewed day by day.", "2 Corinthians 4:16", "You do not have to store strength for the whole journey. Just today's."],
  ["He Will Not Fail", "He will not fail you or forsake you.", "Deuteronomy 31:6", "Discouragement says you are alone. The truth says you never are."],
  ["Keep Your Eyes Up", "I lift up my eyes to the mountains—where does my help come from?", "Psalm 121:1-2", "When the load is heavy, look up. Help comes from the Maker."],
  ["Finish Strong", "Let us run... fixing our eyes on Jesus.", "Hebrews 12:1-2", "The finish is sweeter when you kept your eyes on Him the whole way."],

  // ── SEPTEMBER ──
  ["Get Wisdom", "The beginning of wisdom is this: Get wisdom.", "Proverbs 4:7", "Wisdom does not fall on you. You go after it. Start today."],
  ["Ask for Wisdom", "If any of you lacks wisdom, you should ask God.", "James 1:5", "Stop white-knuckling decisions. Ask the One who knows."],
  ["Fear of the Lord", "The fear of the Lord is the beginning of wisdom.", "Proverbs 9:10", "Reverence for God reorders everything. Start there."],
  ["Listen and Learn", "The way of fools seems right to them, but the wise listen to advice.", "Proverbs 12:15", "You do not know everything. Wise people stay teachable."],
  ["Walk with the Wise", "Walk with the wise and become wise.", "Proverbs 13:20", "You become who you walk with. Choose your company on purpose."],
  ["Guard Your Steps", "Make level paths for your feet.", "Proverbs 4:26", "Think before you move. A measured step beats a regretted leap."],
  ["Choose Your Words", "The words of the reckless pierce like swords, but the tongue of the wise brings healing.", "Proverbs 12:18", "Words can wound or heal. Choose the healing kind."],
  ["Plans and Steps", "In their hearts humans plan their course, but the Lord establishes their steps.", "Proverbs 16:9", "Make the plan, then hold it loosely. He directs the actual steps."],
  ["Two-Edged Wisdom", "Be wise as serpents and innocent as doves.", "Matthew 10:16", "Be sharp without being shady. Wise and clean at the same time."],
  ["Slow Down", "Desire without knowledge is not good—how much more will hasty feet miss the way!", "Proverbs 19:2", "Speed is not the same as progress. Slow down enough to aim."],
  ["Apply Your Heart", "Apply your heart to instruction and your ears to words of knowledge.", "Proverbs 23:12", "Knowledge does nothing on the shelf. Apply it."],
  ["Counsel Wins", "Plans fail for lack of counsel, but with many advisers they succeed.", "Proverbs 15:22", "Do not decide big things alone. Get wise counsel."],
  ["Discern", "Test everything; hold on to what is good.", "1 Thessalonians 5:21", "Do not swallow everything you hear. Test it, keep the good."],
  ["Wisdom from Above", "The wisdom that comes from heaven is first of all pure, then peace-loving.", "James 3:17", "Heaven's wisdom is recognizable: it makes peace, not noise."],
  ["Know the Times", "Make the most of every opportunity.", "Ephesians 5:16", "Read the moment and act. Opportunities do not wait."],
  ["A Disciplined Mind", "We take captive every thought to make it obedient to Christ.", "2 Corinthians 10:5", "Do not let thoughts run wild. Arrest the lies, keep the truth."],
  ["Build on Rock", "Everyone who hears these words of mine and puts them into practice is like a wise man.", "Matthew 7:24", "Hearing is not enough. Wisdom is truth you actually do."],
  ["Stay Focused", "One thing I do: forgetting what is behind... I press on.", "Philippians 3:13-14", "Scattered effort goes nowhere. Pick the one thing and press."],
  ["Weigh Your Words", "The heart of the righteous weighs its answers.", "Proverbs 15:28", "Pause before you respond. The pause is where wisdom lives."],
  ["Stay Humble", "Pride goes before destruction, a haughty spirit before a fall.", "Proverbs 16:18", "Pride blinds you to the cliff. Stay humble and stay standing."],
  ["Number Your Days", "Teach us to number our days.", "Psalm 90:12", "Time is the one thing you cannot earn back. Spend it wisely."],
  ["Right Priorities", "What good is it for someone to gain the whole world, yet forfeit their soul?", "Mark 8:36", "Make sure the ladder you are climbing leans on the right wall."],
  ["Quiet Confidence", "In repentance and rest is your salvation, in quietness and trust is your strength.", "Isaiah 30:15", "You do not have to prove anything. Rest in Him and be strong."],
  ["A Patient Spirit", "The end of a matter is better than its beginning, and patience is better than pride.", "Ecclesiastes 7:8", "Do not bail early. Patience usually wins the long game."],
  ["Light for Decisions", "Your word is a lamp for my feet.", "Psalm 119:105", "When the path is unclear, take it to the Word. It lights the next step."],
  ["Do Not Lean on Yourself", "Do not be wise in your own eyes; fear the Lord and shun evil.", "Proverbs 3:7", "Self-reliance has limits. Defer to the One who sees the whole picture."],
  ["Choose the Good Portion", "Mary has chosen what is better, and it will not be taken away from her.", "Luke 10:42", "Busy is not the same as fruitful. Choose time at His feet."],
  ["Wisdom in Restraint", "Even fools are thought wise if they keep silent.", "Proverbs 17:28", "You rarely regret what you did not say. Practice restraint."],
  ["Stay Rooted", "Like a tree planted by streams of water.", "Psalm 1:3", "Stay near the source and you will not be moved by the seasons."],
  ["Seek Him Early", "Those who seek me find me.", "Proverbs 8:17", "Wisdom is found by those who go looking. Seek early, seek often."],

  // ── OCTOBER ──
  ["Put On the Armor", "Put on the full armor of God.", "Ephesians 6:11", "You do not drift into readiness. You put it on, daily and deliberately."],
  ["Stand Against Schemes", "So that you can take your stand against the devil's schemes.", "Ephesians 6:11", "The enemy plans. So should you. Stand ready."],
  ["Not Flesh and Blood", "Our struggle is not against flesh and blood.", "Ephesians 6:12", "The real fight is unseen. Stop battling people and start battling in prayer."],
  ["The Belt of Truth", "Stand firm then, with the belt of truth buckled around your waist.", "Ephesians 6:14", "Everything else hangs on truth. Buckle it tight."],
  ["Breastplate of Righteousness", "With the breastplate of righteousness in place.", "Ephesians 6:14", "Clean living guards your heart. Protect the core."],
  ["Feet Ready", "With your feet fitted with the readiness that comes from the gospel of peace.", "Ephesians 6:15", "Be ready to move and bring peace wherever you step."],
  ["Shield of Faith", "Take up the shield of faith, with which you can extinguish all the flaming arrows.", "Ephesians 6:16", "Faith is not passive. It blocks the lies aimed at you. Raise it."],
  ["Helmet of Salvation", "Take the helmet of salvation.", "Ephesians 6:17", "Guard your mind with who you are in Christ. The fight starts there."],
  ["The Sword", "And the sword of the Spirit, which is the word of God.", "Ephesians 6:17", "The Word is your one offensive weapon. Know it. Use it."],
  ["Pray in the Spirit", "And pray in the Spirit on all occasions.", "Ephesians 6:18", "Armor on, then pray. Readiness without prayer is just gear."],
  ["Resist", "Resist the devil, and he will flee from you.", "James 4:7", "Submit to God, stand your ground, and watch the enemy back off."],
  ["Be Alert", "Be alert and of sober mind. Your enemy the devil prowls around.", "1 Peter 5:8", "Readiness is not paranoia. It is responsibility. Stay awake."],
  ["Stand Firm", "Be on your guard; stand firm in the faith.", "1 Corinthians 16:13", "When the pressure comes, plant your feet in what you believe."],
  ["Overcome Evil", "Do not be overcome by evil, but overcome evil with good.", "Romans 12:21", "You do not fight darkness with darkness. You flood it with good."],
  ["Weapons with Power", "The weapons we fight with... have divine power to demolish strongholds.", "2 Corinthians 10:4", "Your fight is spiritual, and so is your firepower. Use it."],
  ["Guard the Mind", "Set your minds on things above.", "Colossians 3:2", "The battlefield is the mind. Choose what you let camp there."],
  ["Watch and Pray", "Watch and pray so that you will not fall into temptation.", "Matthew 26:41", "Temptation hunts the distracted. Stay watchful."],
  ["The Lord Is a Warrior", "The Lord is a warrior; the Lord is his name.", "Exodus 15:3", "You do not fight alone. The Warrior fights for you."],
  ["No Weapon", "No weapon forged against you will prevail.", "Isaiah 54:17", "They can forge it. It will not win. Stand secure."],
  ["More Than Conquerors", "In all these things we are more than conquerors through him who loved us.", "Romans 8:37", "Not barely surviving. More than conquering. That is your identity."],
  ["Strong in the Lord", "Finally, be strong in the Lord and in his mighty power.", "Ephesians 6:10", "The armor only works on His strength. Plug into the source."],
  ["Take Your Stand", "And after you have done everything, to stand.", "Ephesians 6:13", "Do the work, then hold. Faithfulness is sometimes just standing."],
  ["Vigilant Heart", "Above all else, guard your heart.", "Proverbs 4:23", "The enemy aims at the heart. Post a guard there."],
  ["Discern the Voice", "My sheep listen to my voice.", "John 10:27", "Learn His voice well enough that the counterfeits stand out."],
  ["Refuse Fear", "When I am afraid, I put my trust in you.", "Psalm 56:3", "Fear will knock. You decide whether to hand it the wheel."],
  ["The Battle Is His", "The battle is the Lord's.", "1 Samuel 17:47", "Show up faithful. Leave the outcome with the One who owns the fight."],
  ["Stand in Evil Days", "So that when the day of evil comes, you may be able to stand your ground.", "Ephesians 6:13", "Get ready before the hard day. Readiness is built in the calm."],
  ["Pull Down Strongholds", "We demolish arguments and every pretension that sets itself up against the knowledge of God.", "2 Corinthians 10:5", "Tear down the lies you have believed. Replace them with truth."],
  ["Be Self-Controlled", "Be alert and self-controlled.", "1 Thessalonians 5:6", "Discipline is armor too. Keep yourself in check."],
  ["He Trains My Hands", "He trains my hands for battle.", "Psalm 18:34", "He does not just send you to fight. He prepares you for it."],
  ["Victory Is Sure", "Thanks be to God! He gives us the victory through our Lord Jesus Christ.", "1 Corinthians 15:57", "You fight from a win, not for one. The victory is already His."],

  // ── NOVEMBER ──
  ["Give Thanks", "Give thanks to the Lord, for he is good; his love endures forever.", "Psalm 107:1", "Gratitude is a discipline, not a mood. Start the day with thanks."],
  ["In Everything", "Give thanks in all circumstances; for this is God's will for you.", "1 Thessalonians 5:18", "Not for everything, but in everything. Find the thanks today."],
  ["Count the Gifts", "Every good and perfect gift is from above.", "James 1:17", "Look around. Most of what you have, you did not earn. Be grateful."],
  ["Enter with Thanks", "Enter his gates with thanksgiving and his courts with praise.", "Psalm 100:4", "Gratitude is the doorway to His presence. Walk through it."],
  ["A Grateful Heart", "Let the peace of Christ rule in your hearts... And be thankful.", "Colossians 3:15", "Thankfulness and peace travel together. Choose one, get both."],
  ["Bless the Lord", "Praise the Lord, my soul, and forget not all his benefits.", "Psalm 103:2", "Forgetting His goodness breeds discontent. Remember on purpose."],
  ["Content", "Godliness with contentment is great gain.", "1 Timothy 6:6", "Wanting less is its own kind of wealth. Practice contentment."],
  ["Daily Provision", "He daily bears our burdens.", "Psalm 68:19", "He does not show up once. He carries you daily. Thank Him for that."],
  ["Overflowing Thanks", "Overflowing with thankfulness.", "Colossians 2:7", "Let gratitude spill out of you onto the people around you."],
  ["Remember", "Remember the wonders he has done.", "1 Chronicles 16:12", "When today is hard, remember what He already brought you through."],
  ["Generous and Grateful", "A generous person will prosper.", "Proverbs 11:25", "Gratitude opens the hand. Give from a thankful heart."],
  ["His Faithfulness", "Great is your faithfulness.", "Lamentations 3:23", "He has not dropped you yet. He will not start now."],
  ["Sacrifice of Praise", "Let us continually offer to God a sacrifice of praise.", "Hebrews 13:15", "Praise when it is easy and when it costs. Both count."],
  ["Satisfied", "He satisfies the thirsty and fills the hungry with good things.", "Psalm 107:9", "He does not give scraps. He satisfies. Come hungry."],
  ["Thankful for People", "I thank my God every time I remember you.", "Philippians 1:3", "Tell someone today that you are grateful for them. Do not assume they know."],
  ["A Cheerful Heart", "A cheerful heart is good medicine.", "Proverbs 17:22", "Gratitude is medicine you can take all day. Use it generously."],
  ["His Goodness", "Taste and see that the Lord is good.", "Psalm 34:8", "Do not just hear about His goodness. Experience it and give thanks."],
  ["Blessed to Bless", "I will bless you... and you will be a blessing.", "Genesis 12:2", "You were blessed to pass it on. Be the blessing today."],
  ["Rejoice and Be Glad", "I will be glad and rejoice in your love.", "Psalm 31:7", "Choose gladness in His love before the day earns it."],
  ["Thanksgiving Heart", "It is good to praise the Lord and make music to your name.", "Psalm 92:1", "Make gratitude a practice, not a holiday. Praise today."],
  ["Humble Thanks", "What do you have that you did not receive?", "1 Corinthians 4:7", "Everything is grace. That truth keeps you humble and thankful."],
  ["The Lord's Doing", "This is the Lord's doing; it is marvelous in our eyes.", "Psalm 118:23", "Give Him credit for the good. He did more than you noticed."],
  ["Refresh Others", "Whoever refreshes others will be refreshed.", "Proverbs 11:25", "Pour into someone today. Gratitude grows when it is shared."],
  ["Provision in the Wilderness", "Your clothes did not wear out and your feet did not swell during these forty years.", "Deuteronomy 8:4", "Even in the wilderness, He provided. He is providing for you now too."],
  ["Praise in the Storm", "Though the fig tree does not bud... yet I will rejoice in the Lord.", "Habakkuk 3:17-18", "Gratitude that survives the storm is the real thing. Hold onto it."],
  ["A Full Cup", "My cup overflows.", "Psalm 23:5", "Look at what is full before you mourn what is missing."],
  ["Give and It Is Given", "Give, and it will be given to you.", "Luke 6:38", "Gratitude and generosity are a loop. Start it today."],
  ["Lord of the Harvest", "The harvest is plentiful.", "Matthew 9:37", "Thank Him for the harvest, then ask Him to send you into it."],
  ["Forever Grateful", "His love endures forever.", "Psalm 136:1", "When everything else changes, His love does not. Rest in that and give thanks."],
  ["Bless This Home", "From the fullness of his grace we have all received grace in place of grace already given.", "John 1:16", "Grace upon grace. Count it today and thank the Giver."],

  // ── DECEMBER ──
  ["The Light Has Come", "The people walking in darkness have seen a great light.", "Isaiah 9:2", "However dark this season feels, the Light has already broken in."],
  ["Hope Is Coming", "For to us a child is born, to us a son is given.", "Isaiah 9:6", "The hope of the world arrived as a child. Hope is not abstract. It has a name."],
  ["Emmanuel", "They will call him Immanuel (which means God with us).", "Matthew 1:23", "He did not stay distant. He came to be with us. You are not alone."],
  ["Do Not Be Afraid", "Do not be afraid. I bring you good news that will cause great joy.", "Luke 2:10", "The first Christmas message was do not fear. It still is."],
  ["A Savior", "Today in the town of David a Savior has been born to you.", "Luke 2:11", "You did not need a teacher or example only. You needed a Savior. He came."],
  ["The Word Became Flesh", "The Word became flesh and made his dwelling among us.", "John 1:14", "God moved into the neighborhood. He is not far from you today."],
  ["Great Joy", "Glory to God in the highest, and on earth peace to those on whom his favor rests.", "Luke 2:14", "Heaven celebrated His coming. Let your heart join in."],
  ["Treasured in the Heart", "Mary treasured up all these things and pondered them in her heart.", "Luke 2:19", "Slow down this season. Treasure what matters. Ponder it."],
  ["The Gift", "Thanks be to God for his indescribable gift!", "2 Corinthians 9:15", "The greatest gift was already given. Everything else is extra."],
  ["Light No Darkness Overcomes", "The light shines in the darkness, and the darkness has not overcome it.", "John 1:5", "Your darkness is real, but it is outmatched. The Light wins."],
  ["For God So Loved", "For God so loved the world that he gave his one and only Son.", "John 3:16", "Christmas is love with skin on. You are that loved."],
  ["Peace on Earth", "He himself is our peace.", "Ephesians 2:14", "Peace is not a feeling to chase. It is a Person who came to you."],
  ["Wonderful Counselor", "And he will be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace.", "Isaiah 9:6", "Whatever you need this season, He is named for it. Call on Him."],
  ["Good News of Great Joy", "I bring you good news that will cause great joy for all the people.", "Luke 2:10", "This joy is not for the few. It is for you. Receive it."],
  ["Born to Save", "She will give birth to a son, and you are to give him the name Jesus.", "Matthew 1:21", "His name means the Lord saves. That is the whole point of the season."],
  ["A Humble King", "You will find a baby wrapped in cloths and lying in a manger.", "Luke 2:12", "The King came low. He still meets you in the humble places."],
  ["Glory Revealed", "We have seen his glory, the glory of the one and only Son.", "John 1:14", "The glory of God showed up in a manger. Look for Him in small places."],
  ["The Long-Awaited", "My eyes have seen your salvation.", "Luke 2:30", "What generations waited for came. What you are waiting for, trust Him with."],
  ["Heaven Came Down", "Praise be to the Lord, the God of Israel, because he has come to his people.", "Luke 1:68", "He came to His people then. He comes to you now. Welcome Him."],
  ["A Light to the Nations", "A light for revelation to the Gentiles.", "Luke 2:32", "The Light was never meant to stay hidden. Carry it into your world."],
  ["The Faithful Promise", "She gave birth to her firstborn, a son.", "Luke 2:7", "Every promise of God leads here. He keeps His word. Trust the rest."],
  ["Worship Him", "On coming to the house, they... bowed down and worshiped him.", "Matthew 2:11", "The right response to His coming is worship. Bow your heart today."],
  ["Bring Your Gift", "They opened their treasures and presented him with gifts.", "Matthew 2:11", "He does not need your gift, but He wants your heart. Bring it."],
  ["Rejoice Greatly", "When they saw the star, they were overjoyed.", "Matthew 2:10", "Seek Him and you will find joy. Keep following the light to Him."],
  ["The True Light", "The true light that gives light to everyone was coming into the world.", "John 1:9", "He lights up everyone who lets Him. Step into the light."],
  ["Grace and Truth", "Full of grace and truth.", "John 1:14", "He came with both grace for your failures and truth for your direction."],
  ["Hope of Glory", "Christ in you, the hope of glory.", "Colossians 1:27", "Christmas is not just God with us. It became God in us. That is your hope."],
  ["Reflect on the Year", "So teach us to number our days, that we may gain a heart of wisdom.", "Psalm 90:12", "Look back with gratitude. Look ahead with purpose. He held it all."],
  ["New Year, Same Faithful God", "Jesus Christ is the same yesterday and today and forever.", "Hebrews 13:8", "Whatever changes next year, He will not. Step into it anchored."],
  ["Finish and Begin", "Forgetting what is behind and straining toward what is ahead, I press on.", "Philippians 3:13-14", "Close the year well. Open the next pressing toward Him."],
  ["Strong to the End", "He who began a good work in you will carry it on to completion.", "Philippians 1:6", "You are not finished, and neither is He. Step into the new year sure of that."],
];

// Holiday devotions auto-trigger on the real date (overriding the day-of-year entry).
export const HOLIDAY_DEVOTIONS = {
  newyear: ["A New Beginning", "See, I am doing a new thing! Now it springs up; do you not perceive it?", "Isaiah 43:19", "A new year is a clean page. Hand the pen to the One who writes the best stories."],
  newyearseve: ["Look Back, Look Up", "Forgetting what is behind and straining toward what is ahead, I press on toward the goal.", "Philippians 3:13-14", "Close this year with gratitude, not regret. He carried you through every day of it."],
  goodfriday: ["It Is Finished", "When he had received the drink, Jesus said, It is finished. With that, he bowed his head and gave up his spirit.", "John 19:30", "The debt you could never pay was paid in full on the cross. Receive it. Rest in it."],
  easter: ["He Is Risen", "He is not here; he has risen, just as he said. Come and see the place where he lay.", "Matthew 28:6", "The grave could not hold Him, and it will not hold you. Live today like death already lost."],
  independence: ["True Freedom", "It is for freedom that Christ has set us free. Stand firm.", "Galatians 5:1", "Be grateful for the freedom you were given, and use the deeper freedom Christ bought to stand for what is right."],
  thanksgiving: ["Give Thanks", "Give thanks to the Lord, for he is good; his love endures forever.", "Psalm 107:1", "Before the meal, before the football, before anything else today — stop and count what He has done. Gratitude changes everything."],
  hanukkah: ["Festival of Lights", "The light shines in the darkness, and the darkness has not overcome it.", "John 1:5", "A season that remembers light in dark times. However dark it feels, the Light still shines, and darkness has never won."],
  christmaseve: ["The Night He Came", "And she gave birth to her firstborn, a son. She wrapped him in cloths and placed him in a manger.", "Luke 2:7", "Tonight, the hope of the world arrived in a borrowed stable. God came close. Let your heart make room for Him."],
  christmas: ["For Unto Us", "For to us a child is born, to us a son is given... And he will be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace.", "Isaiah 9:6", "Merry Christmas. The Savior has come. Whatever you are carrying, lay it at the manger — He came for exactly that."],
};

// Easter (Computus — Anonymous Gregorian algorithm). Returns {month, day}.
function easterDate(year) {
  const a = year % 19, b = Math.floor(year / 100), c = year % 100;
  const d = Math.floor(b / 4), e = b % 4, f = Math.floor((b + 8) / 25);
  const g = Math.floor((b - f + 1) / 3), h = (19 * a + b - d - g + 15) % 30;
  const i = Math.floor(c / 4), k = c % 4, l = (32 + 2 * e + 2 * i - h - k) % 7;
  const m = Math.floor((a + 11 * h + 22 * l) / 451);
  const month = Math.floor((h + l - 7 * m + 114) / 31);
  const day = ((h + l - 7 * m + 114) % 31) + 1;
  return { month, day };
}

// Hanukkah first night (Gregorian) by year — approximate, covers the near future.
const HANUKKAH_FIRST_NIGHT = {
  2025: [12, 14], 2026: [12, 4], 2027: [12, 24], 2028: [12, 12],
  2029: [12, 1], 2030: [12, 20], 2031: [12, 9], 2032: [12, 27],
  2033: [12, 16], 2034: [12, 6], 2035: [12, 25],
};

function holidayKey(d) {
  const y = d.getFullYear(), m = d.getMonth() + 1, day = d.getDate();
  if (m === 1 && day === 1) return "newyear";
  if (m === 12 && day === 31) return "newyearseve";
  if (m === 12 && day === 25) return "christmas";
  if (m === 12 && day === 24) return "christmaseve";
  if (m === 7 && day === 4) return "independence";
  // Thanksgiving — 4th Thursday of November
  if (m === 11) {
    const firstDay = new Date(y, 10, 1).getDay(); // 0=Sun
    const firstThursday = ((4 - firstDay + 7) % 7) + 1;
    if (day === firstThursday + 21) return "thanksgiving";
  }
  // Easter + Good Friday
  const e = easterDate(y);
  if (m === e.month && day === e.day) return "easter";
  const gf = new Date(y, e.month - 1, e.day); gf.setDate(gf.getDate() - 2);
  if (m === gf.getMonth() + 1 && day === gf.getDate()) return "goodfriday";
  // Hanukkah (first night)
  const hk = HANUKKAH_FIRST_NIGHT[y];
  if (hk && m === hk[0] && day === hk[1]) return "hanukkah";
  return null;
}

function toDevotion(entry) {
  return { title: entry[0], verse: entry[1], ref: entry[2], body: entry[3] };
}

// Returns today's devotion: a holiday devotion if today is one, else the day-of-year entry.
export function getTodaysDevotion(date = new Date()) {
  const key = holidayKey(date);
  if (key && HOLIDAY_DEVOTIONS[key]) return { ...toDevotion(HOLIDAY_DEVOTIONS[key]), holiday: true };
  const start = new Date(date.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((date - start) / 86400000); // 1..366
  const idx = (dayOfYear - 1) % DAILY_DEVOTIONS.length;
  return { ...toDevotion(DAILY_DEVOTIONS[idx]), holiday: false };
}
